### ISSUE TITLE
couldn't find preset "es2015" when using as dependency

### ISSUE THREAD

**Issue by agirault** [Kitware/itk-vtk-image-viewer#30]
When adding `itk-vtk-viewer` as a dependency, I get the following error when running `build`:

```
ERROR in ./node_modules/itk-vtk-image-viewer/src/convertItkImageToVtkImage.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "source/node_modules/itk-vtk-image-viewer"
    at source/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (source/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (source/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (source/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (source/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (source/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (source/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (source/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (source/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (source/node_modules/babel-loader/lib/index.js:175:20)
 @ ./node_modules/babel-loader/lib?{"presets":["env"]}!./node_modules/eslint-loader?{"configFile":"source/node_modules/vtk.js/.eslintrc.js"}!./src/index.js 7:33-94
 @ ./src/index.js-exposed
```

Fixed by adding the following to the package.json (dependencies) of the top level project:
`"babel-preset-es2015": "^6.24.1"`

**Comment by thewtex** [comment]
Should be addressed by #32 or #45
